#!/usr/bin/env python3
"""
run_backtest.py — EMPIREX-OS Quant Engine · Main Runner
=========================================================

WARNING: Results from --demo mode use SYNTHETIC data generated by a random
walk model. They do NOT reflect real market conditions and MUST NOT be used
for live trading decisions. All demo output is clearly labelled SIMULATED.

Usage examples
--------------
  # Demo mode (synthetic data, no network required):
  python run_backtest.py --demo --symbol EURUSD

  # Real data from a CSV file:
  python run_backtest.py --symbol EURUSD --strategy LRB \
      --start 2026-01-01 --end 2026-06-01 \
      --data-file /path/to/EURUSD_H1.csv

  # Real data from yfinance (requires: pip install yfinance):
  python run_backtest.py --symbol EURUSD --strategy both \
      --start 2026-01-01 --end 2026-06-28

Supported symbols   : EURUSD, GBPUSD, XAUUSD, NAS100
Supported strategies: LRB, EMP, both (default)

CSV format expected (column names are case-insensitive):
  datetime, open, high, low, close[, volume]
  datetime must be parseable as UTC timestamps.

yfinance ticker map:
  EURUSD → EURUSD=X
  GBPUSD → GBPUSD=X
  XAUUSD → GC=F  (Gold futures — 1H)
  NAS100 → NQ=F  (Nasdaq 100 futures — 1H)
"""

from __future__ import annotations

# ============================================================
# WARNING — displayed before ANY import so it is always seen
# ============================================================
import sys

_DEMO_WARNING = """
================================================================================
  WARNING: --demo mode produces SYNTHETIC (randomly generated) price data.
  Results are SIMULATED and MUST NOT be used for live trading decisions.
  All synthetic output is labelled [SIMULATED] throughout this report.
================================================================================
"""

# ---------------------------------------------------------------------------
import argparse
import math
import os
import warnings
from datetime import datetime, timezone
from typing import Optional

import numpy as np
import pandas as pd

# ---------------------------------------------------------------------------
# Local modules
# ---------------------------------------------------------------------------
_DIR = os.path.dirname(os.path.abspath(__file__))
if _DIR not in sys.path:
    sys.path.insert(0, _DIR)

from backtest_engine import BacktestEngine, INSTRUMENT_SPECS
from strategies import LRBStrategy, EMPSessionMomentumStrategy
from reporting import (
    PerformanceReporter,
    print_benchmark_comparison,
    export_benchmark_comparison_csv,
)


# ===========================================================================
# Synthetic data generator
# ===========================================================================

def generate_synthetic_ohlcv(
    symbol: str,
    start: str = "2026-01-01",
    end: str = "2026-06-28",
    seed: int = 42,
) -> pd.DataFrame:
    """
    Generate synthetic 1H OHLCV bars using a geometric random walk.

    THIS DATA IS ENTIRELY FICTIONAL.  It is provided only to demonstrate
    that the framework runs correctly end-to-end.  No inference about real
    markets should be drawn from synthetic results.

    Parameters
    ----------
    symbol : one of EURUSD, GBPUSD, XAUUSD, NAS100
    start / end : date strings (inclusive)
    seed : random seed for reproducibility

    Returns
    -------
    pd.DataFrame with DatetimeIndex (UTC) and columns: open, high, low, close, volume
    """
    rng = np.random.default_rng(seed)

    SEED_PRICES = {
        "EURUSD": 1.05000,
        "GBPUSD": 1.25000,
        "XAUUSD": 2300.00,
        "NAS100": 17500.0,
    }
    VOLATILITY = {           # per-bar log-return std dev (hourly)
        "EURUSD": 0.00030,
        "GBPUSD": 0.00035,
        "XAUUSD": 0.00120,
        "NAS100": 0.00200,
    }
    SPREAD_FACTOR = {
        "EURUSD": 0.00020,
        "GBPUSD": 0.00022,
        "XAUUSD": 0.50,
        "NAS100": 3.0,
    }

    idx = pd.date_range(start=start, end=end, freq="1h", tz="UTC")
    # Remove weekends (FX / index markets mostly closed)
    idx = idx[idx.dayofweek < 5]
    n = len(idx)

    vol = VOLATILITY[symbol]
    price = SEED_PRICES[symbol]
    spread = SPREAD_FACTOR[symbol]

    closes = np.zeros(n)
    opens = np.zeros(n)
    highs = np.zeros(n)
    lows = np.zeros(n)
    volumes = rng.integers(500, 5000, size=n).astype(float)

    cur = price
    for i in range(n):
        # Simulate intrabar behaviour with 4 sub-ticks
        ret = rng.normal(0, vol)
        # Mild mean-reversion to seed price
        ret += (math.log(price) - math.log(cur)) * 0.001
        o = cur
        ticks = [cur * math.exp(rng.normal(0, vol * 0.5)) for _ in range(4)]
        c = cur * math.exp(ret)
        ticks.append(c)
        h = max(max(ticks), o, c) + spread * 0.5
        l = min(min(ticks), o, c) - spread * 0.5
        opens[i] = o
        closes[i] = c
        highs[i] = h
        lows[i] = max(l, c * 0.98)  # floor to avoid negative
        cur = c

    df = pd.DataFrame(
        {"open": opens, "high": highs, "low": lows, "close": closes, "volume": volumes},
        index=idx,
    )
    return df


# ===========================================================================
# Data loaders
# ===========================================================================

def load_csv(path: str, symbol: str) -> pd.DataFrame:
    """
    Load OHLCV data from a CSV file.
    Expects columns (case-insensitive): datetime, open, high, low, close[, volume]
    datetime column is parsed as UTC.
    """
    df = pd.read_csv(path)
    df.columns = df.columns.str.lower().str.strip()

    # Find datetime column
    dt_col = None
    for c in ("datetime", "date", "time", "timestamp", "date_time"):
        if c in df.columns:
            dt_col = c
            break
    if dt_col is None:
        raise ValueError(
            f"Cannot find datetime column in {path}. "
            "Expected one of: datetime, date, time, timestamp"
        )

    df[dt_col] = pd.to_datetime(df[dt_col], utc=True)
    df = df.set_index(dt_col)
    df.index.name = "datetime"

    required = {"open", "high", "low", "close"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"CSV missing columns: {missing}")

    if "volume" not in df.columns:
        df["volume"] = 1.0

    df = df[["open", "high", "low", "close", "volume"]].astype(float)
    df.sort_index(inplace=True)
    return df


def load_yfinance(symbol: str, start: str, end: str) -> pd.DataFrame:
    """
    Download 1H OHLCV bars from yfinance.
    Requires: pip install yfinance
    """
    try:
        import yfinance as yf
    except ImportError:
        raise ImportError(
            "yfinance is not installed. Run: pip install yfinance\n"
            "Or supply a CSV file with --data-file."
        )

    TICKER_MAP = {
        "EURUSD": "EURUSD=X",
        "GBPUSD": "GBPUSD=X",
        "XAUUSD": "GC=F",
        "NAS100": "NQ=F",
    }
    ticker = TICKER_MAP.get(symbol.upper())
    if ticker is None:
        raise ValueError(f"No yfinance ticker mapping for symbol: {symbol}")

    print(f"[INFO] Downloading {symbol} ({ticker}) from yfinance ...")
    raw = yf.download(ticker, start=start, end=end, interval="1h", auto_adjust=True, progress=False)
    if raw.empty:
        raise RuntimeError(
            f"yfinance returned no data for {ticker} between {start} and {end}."
        )

    raw.columns = [c.lower() for c in raw.columns]
    # yfinance may return a MultiIndex; flatten if needed
    if isinstance(raw.columns, pd.MultiIndex):
        raw.columns = raw.columns.get_level_values(0)

    if raw.index.tz is None:
        raw.index = raw.index.tz_localize("UTC")
    else:
        raw.index = raw.index.tz_convert("UTC")

    df = raw[["open", "high", "low", "close", "volume"]].copy().astype(float)
    df.sort_index(inplace=True)
    return df


# ===========================================================================
# Runner
# ===========================================================================

def run_strategy(
    symbol: str,
    strategy_name: str,
    df: pd.DataFrame,
    start: pd.Timestamp,
    end: pd.Timestamp,
    initial_capital: float,
    lot_size: float,
    is_simulated: bool,
) -> PerformanceReporter:
    """Run a single strategy on a single symbol and return a reporter."""
    # Filter to requested date range
    df_range = df[(df.index >= start) & (df.index <= end)].copy()

    if df_range.empty:
        print(f"[WARN] No data for {symbol} between {start.date()} and {end.date()}")
        # Return an empty reporter
        empty_results = {
            "symbol": symbol,
            "strategy": strategy_name,
            "initial_capital": initial_capital,
            "final_equity": initial_capital,
            "trades": pd.DataFrame(),
            "equity_curve": pd.Series([initial_capital]),
        }
        return PerformanceReporter(empty_results, start, end, is_simulated)

    if strategy_name == "LRB":
        strategy = LRBStrategy()
    elif strategy_name in ("EMP", "EMPSessionMomentum"):
        strategy = EMPSessionMomentumStrategy()
    else:
        raise ValueError(f"Unknown strategy: {strategy_name}")

    engine = BacktestEngine(
        symbol=symbol,
        strategy_name=strategy_name,
        initial_capital=initial_capital,
        lot_size=lot_size,
    )
    engine.run(df_range, strategy)
    results = engine.get_results()

    return PerformanceReporter(results, start, end, is_simulated)


# ===========================================================================
# CLI entry point
# ===========================================================================

def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description=(
            "EMPIREX-OS Python Backtesting Framework\n"
            "----------------------------------------\n"
            "Run London Range Breakout (LRB) and EMP Session Momentum strategies.\n\n"
            "WARNING: --demo mode uses SYNTHETIC data. NOT for live trading."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument(
        "--demo",
        action="store_true",
        help="Run with SYNTHETIC data for demonstration. Labels output [SIMULATED].",
    )
    p.add_argument(
        "--symbol",
        type=str,
        default="EURUSD",
        choices=list(INSTRUMENT_SPECS.keys()),
        help="Instrument to backtest (default: EURUSD)",
    )
    p.add_argument(
        "--strategy",
        type=str,
        default="both",
        choices=["LRB", "EMP", "both"],
        help="Strategy to run: LRB | EMP | both (default: both)",
    )
    p.add_argument(
        "--start",
        type=str,
        default="2026-01-01",
        help="Backtest start date YYYY-MM-DD UTC (default: 2026-01-01)",
    )
    p.add_argument(
        "--end",
        type=str,
        default="2026-06-28",
        help="Backtest end date YYYY-MM-DD UTC (default: 2026-06-28)",
    )
    p.add_argument(
        "--data-file",
        type=str,
        default=None,
        help="Path to CSV file with OHLCV data (overrides yfinance download)",
    )
    p.add_argument(
        "--initial-capital",
        type=float,
        default=10_000.0,
        help="Starting account equity in USD (default: 10000)",
    )
    p.add_argument(
        "--lot-size",
        type=float,
        default=0.1,
        help="Lot size for each trade (default: 0.1)",
    )
    p.add_argument(
        "--output-dir",
        type=str,
        default="./backtest_results",
        help="Directory for CSV export (default: ./backtest_results)",
    )
    p.add_argument(
        "--no-csv",
        action="store_true",
        help="Skip CSV export",
    )
    p.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for --demo synthetic data (default: 42)",
    )
    return p


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    # ---- Print demo warning first ----
    if args.demo:
        print(_DEMO_WARNING)

    start = pd.Timestamp(args.start, tz="UTC")
    end = pd.Timestamp(args.end, tz="UTC")

    if start >= end:
        parser.error("--start must be before --end")

    symbol = args.symbol.upper()
    is_simulated = args.demo

    # ---- Load data ----
    if args.demo:
        print(f"[SIMULATED] Generating synthetic OHLCV data for {symbol} ...")
        df = generate_synthetic_ohlcv(
            symbol=symbol,
            start=args.start,
            end=args.end,
            seed=args.seed,
        )
        print(f"[SIMULATED] Generated {len(df):,} bars from {df.index[0]} to {df.index[-1]}")
    elif args.data_file:
        print(f"[INFO] Loading data from {args.data_file} ...")
        df = load_csv(args.data_file, symbol)
        print(f"[INFO] Loaded {len(df):,} bars from {df.index[0]} to {df.index[-1]}")
    else:
        df = load_yfinance(symbol, args.start, args.end)
        print(f"[INFO] Downloaded {len(df):,} bars from {df.index[0]} to {df.index[-1]}")

    if df.empty:
        print("[ERROR] No data loaded. Exiting.")
        sys.exit(1)

    # ---- Determine strategies to run ----
    strategies_to_run = []
    if args.strategy == "both":
        strategies_to_run = ["LRB", "EMP"]
    else:
        strategies_to_run = [args.strategy]

    # ---- Run strategies ----
    reporters: list[PerformanceReporter] = []
    for strat in strategies_to_run:
        print(f"\n[INFO] Running {strat} strategy on {symbol} ...")
        try:
            reporter = run_strategy(
                symbol=symbol,
                strategy_name=strat,
                df=df,
                start=start,
                end=end,
                initial_capital=args.initial_capital,
                lot_size=args.lot_size,
                is_simulated=is_simulated,
            )
            reporters.append(reporter)
        except Exception as exc:
            print(f"[ERROR] Strategy {strat} failed: {exc}")
            import traceback
            traceback.print_exc()
            continue

    if not reporters:
        print("[ERROR] No strategies completed successfully.")
        sys.exit(1)

    # ---- Print results ----
    if args.demo:
        print("\n" + "!" * 70)
        print("!!! ALL RESULTS BELOW ARE FROM SIMULATED (SYNTHETIC) DATA !!!!")
        print("!!! DO NOT USE THESE NUMBERS FOR LIVE TRADING DECISIONS    !!!!")
        print("!" * 70)

    for r in reporters:
        r.print_all()

    if len(reporters) > 1:
        print_benchmark_comparison(reporters)

    # ---- CSV export ----
    if not args.no_csv:
        output_dir = args.output_dir
        print(f"\n[INFO] Exporting results to {output_dir}/ ...")
        all_files = []
        for r in reporters:
            files = r.export_csv(output_dir)
            all_files.extend(files)

        if len(reporters) > 1:
            cmp_file = export_benchmark_comparison_csv(reporters, output_dir)
            all_files.append(cmp_file)

        for f in all_files:
            print(f"  [CSV] {f}")

    # ---- Final reminder for demo ----
    if args.demo:
        print(_DEMO_WARNING)

    print("\n[INFO] Backtest complete.")


# ===========================================================================
# Self-test (quick smoke test with synthetic data)
# ===========================================================================

def _self_test() -> None:
    """
    Quick smoke test — runs both strategies on synthetic data for each
    supported symbol and asserts basic sanity checks.
    Invoked with: python run_backtest.py --self-test
    """
    print("\n[SELF-TEST] Running smoke tests with SYNTHETIC data ...")
    errors = []
    symbols = list(INSTRUMENT_SPECS.keys())
    strategies = [("LRB", LRBStrategy), ("EMP", EMPSessionMomentumStrategy)]

    for sym in symbols:
        df = generate_synthetic_ohlcv(sym, "2026-01-01", "2026-03-31", seed=7)
        for strat_name, StratCls in strategies:
            try:
                engine = BacktestEngine(sym, strat_name, initial_capital=10_000, lot_size=0.1)
                engine.run(df, StratCls())
                res = engine.get_results()
                assert isinstance(res["trades"], pd.DataFrame), "Trades not a DataFrame"
                assert isinstance(res["equity_curve"], pd.Series), "Equity curve not a Series"
                print(f"  [OK] {sym} / {strat_name} — {len(res['trades'])} trades")
            except Exception as e:
                errors.append(f"{sym}/{strat_name}: {e}")
                print(f"  [FAIL] {sym} / {strat_name}: {e}")

    if errors:
        print(f"\n[SELF-TEST] FAILED — {len(errors)} error(s):")
        for e in errors:
            print(f"  {e}")
        sys.exit(1)
    else:
        print("\n[SELF-TEST] All tests passed.")


# ===========================================================================

if __name__ == "__main__":
    # Handle --self-test as a special flag before argparse
    if "--self-test" in sys.argv:
        _self_test()
    else:
        main()
